Support sphinx 5
executablebooks/sphinx-external-toc pull request #85
Opened 2022-10-06 10:29 UTC by coretl

Sphinx 5 seems to work with sphinx-external-tox in my projects. Pushing it here to see if it breaks CI...

2022-11-09 17:58 UTC, jpoa submitted a review, later dismissed
It is working for me as well

2022-11-14 04:02 UTC, AakashGfude approved these changes

2022-11-14 04:08 UTC, mmcky commented
thanks @coretl for this update. Greatly appreciated. Sorry it has taken so long to loop around to it. We are currently in the process of updating a number of `executable books` projects to `sphinx5` so we can release the next version of `jupyter book`.

2022-11-14 04:09 UTC, mmcky requested changes

2022-11-14 04:09 UTC, mmcky commented on pyproject.toml
> +    "sphinx>=3,<6",
```suggestion
    "sphinx>=4,<6",
```

@coretl you are correct re: style guide. I think this should be `>=4,<6`

2022-11-14 04:11 UTC, mmcky commented on pyproject.toml
> +    "sphinx>=3,<6",
@AakashGfude feel free to merge after your review. We can update the lower bound as part of the release.

2022-11-14 04:20 UTC, mmcky commented
@AakashGfude when running this through `tox` and enforcing `sphinx==5.3.0` there are a number of deprecation warnings we should attend to:

```
tests/test_sphinx.py: 47 warnings
  /Users/mmcky/work/executablebooks/sphinx-external-toc/sphinx_external_toc/events.py:167: PendingDeprecationWarning: nodes.Node.traverse() is obsoleted by Node.findall().
    for node in doctree.traverse(toctree_node):

tests/test_sphinx.py: 47 warnings
  /Users/mmcky/work/executablebooks/sphinx-external-toc/sphinx_external_toc/events.py:177: PendingDeprecationWarning: nodes.Node.traverse() is obsoleted by Node.findall().
    doctree.traverse(TableOfContentsNode)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

2022-11-14 04:49 UTC, mmcky commented
@chrisjsewell I went through this PR and updated it to resolve the warnings being issued by `tox` for the `docutils` issue around `traverse` and `findall`. Would you mind reviewing this PR?

2022-11-21 09:34 UTC, chrisjsewell approved these changes
looks good to me cheers

2022-11-24 00:57 UTC, mmcky commented on pyproject.toml
> +    "sphinx>=3,<6",
This has been resolved

2022-11-24 00:57 UTC, mmcky approved these changes

2022-11-24 00:57 UTC, merged